### ISSUE TITLE
Ad close button does nothing

### ISSUE THREAD

**Issue by alexandre97costa** [FrontendMasters/front-end-handbook-2024#10]
Up top on the page, there's a Frontend Masters ad with a close button that does not close/dismiss the ad

![image](https://github.com/FrontendMasters/front-end-handbook-2024/assets/38655930/7278a138-26fa-4b7e-99aa-a64348da1665)

**Comment by 1Marc** [comment]
I removed the close button. If there's a better place to put the call to action, I'm open to ideas. But we want folks to try our free courses, they are great.
