### ISSUE TITLE
Table layout not responsive on mobile devices

### ISSUE THREAD

**Issue by pravinkori** [FrontendMasters/front-end-handbook-2024#11]
The table layout is not responsive on mobile devices. The text is too small and wrapping incorrectly, This makes it difficult to read the table.

![Fm-table](https://github.com/FrontendMasters/front-end-handbook-2024/assets/58039953/48f58a89-2911-4c29-883e-6ebaac687baa)

**Comment by Sheryar-bit** [comment]
can I work on this issue?

**Comment by 1Marc** [comment]
It looks like @picajoso fixed this a bit, but if you want to work on it more, be my guest!
