### ISSUE TITLE
Typo in 6.81 Web Typogrpahy :)

### ISSUE THREAD

**Issue by picajoso** [FrontendMasters/front-end-handbook-2024#18]
![Captura de pantalla 2024-04-25 a las 13 00 04](https://github.com/FrontendMasters/front-end-handbook-2024/assets/853760/158df816-e6f4-45e4-8bd2-b21aedbf1a95)

**Comment by Sheryar-bit** [comment]
I am working on this issue

**Comment by 1Marc** [comment]
Thanks!
