### ISSUE TITLE
better meta tags for the preview offered by the site when shared

### ISSUE THREAD

**Issue by t-var-s** [FrontendMasters/front-end-handbook-2024#20]
Current title + description offer this preview: 

The (Frontend||UI||UX) Developer/Engineer Handbook 2024
Front-end Developer Handbook 2024

The easiest upgrade is to just use the cover to add an image to the preview. I can make a pull request for that. 

Meanwhile, you may want to consider a cleaner title + description? Maybe the title can be "The Front End Developer/Engineer Handbook 2024" and the description "Written by Cody Lindley for Frontend Masters"?

**Comment by 1Marc** [comment]
A PR would be great!

**Comment by Sheryar-bit** [comment]
Can I work on this issue ?

**Comment by 1Marc** [comment]
thanks again!
