### ISSUE TITLE
Scrollbars are always in light mode regardless of the theme switch

### ISSUE THREAD

**Issue by aditiintechk** [FrontendMasters/front-end-handbook-2024#21]
Hi,

Found that the scrollbar is always in light mode regardless of the theme switch, I can take up the issue and fix it. Please assign it to me if possible. Find the screenshot for reference below.

Thanks
Aditi

![screenshot](https://github.com/FrontendMasters/front-end-handbook-2024/assets/96046912/6c65c0cc-24df-4f16-88f6-f0d7d5aa3f45)

**Comment by 1Marc** [comment]
A PR would be great!

**Comment by Sheryar-bit** [comment]
> A PR would be great!

Are you working on this issue otherwise Can I work ?

**Comment by Aditi002-holo** [comment]
Hi @1Marc - A PR has been created. Thanks.

**Comment by 1Marc** [comment]
accepted, thanks!
