### ISSUE TITLE
Link misplacement

### ISSUE THREAD

**Issue by marthamwangi** [FrontendMasters/front-end-handbook-2024#6]
Interchange these links
Jobs on [wellfound.com](https://www.indeed.com/)
Jobs on [indeed.com](https://wellfound.com/jobs)

**Comment by salmanfarisvp** [comment]
I raised an PR with the fix https://github.com/FrontendMasters/front-end-handbook-2024/pull/7

**Comment by marthamwangi** [comment]
Ah! Okay
